stages:
  data_ingestion:
    cmd: python src/cnnClassificationProject/pipeline/stage_01_data_ingestion.py
    deps:
      - src/cnnClassificationProject/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/Chest-CT-Scan-data

  prepare_base_model:
    cmd: python src/cnnClassificationProject/pipeline/stage_02_prepare_base_model.py
    deps:
    - src/cnnClassificationProject/pipeline/stage_02_prepare_base_model.py
    - config/config.yaml
    params:
    - IMAGE_SIZE
    - INCLUDE_TOP
    - CLASSES
    - WEIGHTS
    - LEARNING_RATE
    outs:
    - artifacts/prepare_base_model

  training:
    cmd: python src/cnnClassificationProject/pipeline/stage_03_model_training.py
    deps:
    - src/cnnClassificationProject/pipeline/stage_03_model_training.py
    - config/config.yaml
    - artifacts/data_ingestion/Chest-CT-Scan-data
    - artifacts/prepare_base_model
    params:
    - IMAGE_SIZE
    - EPOCHS
    - BATCH_SIZE
    - AUGMENTATION
    outs:
    - artifacts/training/model.h5

  evaluation:
    cmd: python src/cnnClassificationProject/pipeline/stage_04_model_evaluation_mlflow.py
    deps:
    - src/cnnClassificationProject/pipeline/stage_04_model_evaluation_mlflow.py
    - config/config.yaml
    - artifacts/data_ingestion/Chest-CT-Scan-data
    - artifacts/training/model.h5
    params:
    - IMAGE_SIZE
    - BATCH_SIZE
    metrics:
    - score.json:
        cache: false
